export const contractsResource = {
  key: 'contracts',
  endpoint: '/api/v1/contracts',
  navKey: 'contracts',
  columns: [
    { key: 'contract_number', label: 'Contract number', sortable: true },
    { key: 'property_name', label: 'Property' },
    { key: 'tenant_name', label: 'Tenant' },
    { key: 'owner_name', label: 'Owner' },
    { key: 'start_date', label: 'Start date', date: true, sortable: true },
    { key: 'end_date', label: 'End date', date: true, sortable: true },
    { key: 'monthly_rent', label: 'Monthly rent', sortable: true, numeric: true, currency: true },
    { key: 'deposit', label: 'Deposit', sortable: true, numeric: true, currency: true },
    { key: 'status', label: 'Status' },
    { key: 'created_at', label: 'Created at', datetime: true, hiddenByDefault: true },
    { key: 'updated_at', label: 'Updated at', datetime: true, hiddenByDefault: true },
  ],
  fields: [
    { name: 'contract_number', label: 'Contract number', type: 'text', hint: 'Leave blank to auto-generate' },
    { name: 'property_id', label: 'Property', type: 'relation-select', endpoint: '/api/v1/properties', labelField: 'name', required: true },
    { name: 'tenant_id', label: 'Tenant', type: 'relation-select', endpoint: '/api/v1/tenants', labelField: 'name', required: true },
    { name: 'owner_id', label: 'Owner', type: 'relation-select', endpoint: '/api/v1/owners', labelField: 'name' },
    { name: 'start_date', label: 'Start date', type: 'date', required: true },
    { name: 'end_date', label: 'End date', type: 'date', required: true },
    { name: 'monthly_rent', label: 'Monthly rent', type: 'number', required: true, default: 0 },
    { name: 'deposit', label: 'Deposit', type: 'number', required: true, default: 0 },
    { name: 'status', label: 'Status', type: 'text', required: true, default: 'active' },
  ],
};
