export const maintenanceRequestsResource = {
  key: 'maintenance-requests',
  endpoint: '/api/v1/maintenance-requests',
  navKey: 'maintenance_requests',
  columns: [
    { key: 'order_number', label: 'Order number' },
    { key: 'property_name', label: 'Property' },
    { key: 'tenant_id', label: 'Tenant', lookup: { endpoint: '/api/v1/tenants', labelField: 'name' } },
    { key: 'owner_id', label: 'Owner', lookup: { endpoint: '/api/v1/owners', labelField: 'name' } },
    { key: 'title', label: 'Title', sortable: true },
    { key: 'problem_type', label: 'Problem type' },
    { key: 'status', label: 'Status' },
    { key: 'priority', label: 'Priority' },
    { key: 'created_at', label: 'Created at', datetime: true, hiddenByDefault: true },
    { key: 'updated_at', label: 'Updated at', datetime: true, hiddenByDefault: true },
  ],
  fields: [
    { name: 'property_id', label: 'Property', type: 'relation-select', endpoint: '/api/v1/properties', labelField: 'name' },
    { name: 'tenant_id', label: 'Tenant', type: 'relation-select', endpoint: '/api/v1/tenants', labelField: 'name' },
    { name: 'owner_id', label: 'Owner', type: 'relation-select', endpoint: '/api/v1/owners', labelField: 'name' },
    { name: 'title', label: 'Title', type: 'text', required: true },
    { name: 'title_ar', label: 'Title (Arabic)', type: 'text' },
    { name: 'problem_type', label: 'Problem type', type: 'text' },
    { name: 'problem_type_ar', label: 'Problem type (Arabic)', type: 'text' },
    { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    { name: 'description_ar', label: 'Description (Arabic)', type: 'textarea', fullWidth: true },
    { name: 'status', label: 'Status', type: 'text', required: true, default: 'in_progress' },
    { name: 'priority', label: 'Priority', type: 'text', required: true, default: 'medium' },
  ],
};
