export const projectsResource = {
  key: 'projects',
  endpoint: '/api/v1/projects',
  navKey: 'projects',
  columns: [
    { key: 'owner_id', label: 'Owner', lookup: { endpoint: '/api/v1/owners', labelField: 'name' } },
    { key: 'property_id', label: 'Property', lookup: { endpoint: '/api/v1/properties', labelField: 'name' } },
    { key: 'name', label: 'Name', sortable: true },
    { key: 'location', label: 'Location' },
    { key: 'status', label: 'Status' },
    { key: 'progress', label: 'Progress', sortable: true, numeric: true },
    { key: 'budget', label: 'Budget', sortable: true, numeric: true, currency: true },
    { key: 'paid_amount', label: 'Paid amount', sortable: true, numeric: true, currency: true },
    { key: 'start_date', label: 'Start date', date: true, sortable: true },
    { key: 'end_date', label: 'End date', date: true, sortable: true },
    { key: 'created_at', label: 'Created at', datetime: true, hiddenByDefault: true },
    { key: 'updated_at', label: 'Updated at', datetime: true, hiddenByDefault: true },
  ],
  fields: [
    { name: 'owner_id', label: 'Owner', type: 'relation-select', endpoint: '/api/v1/owners', labelField: 'name' },
    { name: 'property_id', label: 'Property', type: 'relation-select', endpoint: '/api/v1/properties', labelField: 'name' },
    { name: 'name', label: 'Name', type: 'text', required: true },
    { name: 'name_ar', label: 'Name (Arabic)', type: 'text' },
    { name: 'location', label: 'Location', type: 'text' },
    { name: 'location_ar', label: 'Location (Arabic)', type: 'text' },
    { name: 'status', label: 'Status', type: 'text', required: true, default: 'under_construction' },
    { name: 'progress', label: 'Progress', type: 'number', required: true, default: 0 },
    { name: 'budget', label: 'Budget', type: 'number', required: true, default: 0 },
    { name: 'paid_amount', label: 'Paid amount', type: 'number', required: true, default: 0 },
    { name: 'start_date', label: 'Start date', type: 'date' },
    { name: 'end_date', label: 'End date', type: 'date' },
    { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    { name: 'description_ar', label: 'Description (Arabic)', type: 'textarea', fullWidth: true },
  ],
};
