export const propertiesResource = {
  key: 'properties',
  endpoint: '/api/v1/properties',
  navKey: 'properties',
  columns: [
    { key: 'owner_name', label: 'Owner' },
    { key: 'name', label: 'Name', sortable: true },
    { key: 'type', label: 'Type' },
    { key: 'location', label: 'Location' },
    { key: 'address', label: 'Address' },
    { key: 'status', label: 'Status', badge: true },
    { key: 'area', label: 'Area', sortable: true, numeric: true },
    { key: 'monthly_revenue', label: 'Monthly revenue', sortable: true, numeric: true, currency: true },
    { key: 'created_at', label: 'Created at', datetime: true, hiddenByDefault: true },
    { key: 'updated_at', label: 'Updated at', datetime: true, hiddenByDefault: true },
  ],
  fields: [
    { name: 'owner_id', label: 'Owner', type: 'relation-select', endpoint: '/api/v1/owners', labelField: 'name' },
    { name: 'name', label: 'Name', type: 'text', required: true },
    { name: 'name_ar', label: 'Name (Arabic)', type: 'text' },
    { name: 'type', label: 'Type', type: 'text', required: true, default: 'apartment' },
    { name: 'location', label: 'Location', type: 'text' },
    { name: 'location_ar', label: 'Location (Arabic)', type: 'text' },
    { name: 'address', label: 'Address', type: 'text' },
    { name: 'address_ar', label: 'Address (Arabic)', type: 'text' },
    { name: 'status', label: 'Status', type: 'text', required: true, default: 'available' },
    { name: 'area', label: 'Area', type: 'number' },
    { name: 'monthly_revenue', label: 'Monthly revenue', type: 'number', required: true, default: 0 },
    { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    { name: 'description_ar', label: 'Description (Arabic)', type: 'textarea', fullWidth: true },
  ],
};
