export const usersResource = {
  key: 'users',
  endpoint: '/api/v1/users',
  navKey: 'users',
  columns: [
    { key: 'name', label: 'Name', sortable: true },
    { key: 'email', label: 'Email address' },
    { key: 'email_verified_at', label: 'Email verified at', datetime: true, sortable: true },
    { key: 'phone', label: 'Phone' },
    { key: 'role', label: 'Role' },
    { key: 'is_admin', label: 'Admin', boolean: true },
    { key: 'locale', label: 'Locale' },
    { key: 'status', label: 'Status' },
    { key: 'address', label: 'Address' },
    { key: 'created_at', label: 'Created at', datetime: true, hiddenByDefault: true },
    { key: 'updated_at', label: 'Updated at', datetime: true, hiddenByDefault: true },
  ],
  fields: [
    { name: 'name', label: 'Name', type: 'text', required: true },
    { name: 'email', label: 'Email address', type: 'text', inputType: 'email', required: true },
    { name: 'email_verified_at', label: 'Email verified at', type: 'datetime' },
    {
      name: 'password',
      label: 'Password',
      type: 'text',
      inputType: 'password',
      omitIfEmpty: true,
      hint: 'Leave blank to keep the current password',
    },
    { name: 'phone', label: 'Phone', type: 'text', inputType: 'tel' },
    { name: 'role', label: 'Role', type: 'text', required: true, default: 'owner' },
    { name: 'is_admin', label: 'Admin', type: 'checkbox' },
    { name: 'locale', label: 'Locale', type: 'text', required: true, default: 'ar' },
    { name: 'status', label: 'Status', type: 'text', required: true, default: 'active' },
    { name: 'address', label: 'Address', type: 'text' },
  ],
};
